conda install -y pip
conda install -y pandas
conda install -y numpy
conda install -y matplotlib
conda install -y seaborn
conda install -y scipy
conda install -y ipykernel
conda install -y jupyter
conda install -y tqdm
conda install -y neo4j
conda install -y networkx
